from abc import ABC, abstractmethod


class LLMService(ABC):
    """
    Base interface for every Large Language Model provider.
    """

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
        Generate a response from the LLM.

        Parameters
        ----------
        prompt : str
            Final prompt generated by PromptBuilder.

        Returns
        -------
        str
            Generated response.
        """
        raise NotImplementedError